%{
/// @file
/// @brief this lexer part of parser was autogenerated by `flex ByteCompiler.lex`
/// @defgroup parser Syntax parser
/// @ingroup bc

#include "ByteCompiler.hpp"
%}

%option noyywrap yylineno

%%

#[^\n]*			{}						// line comment
[ \t\r\n]+		{}						// drop spaces

\.save			return SAVE;
[A-Z0-9_]+\.bc	{ yylval.bcfile = yytext; return BCFILE; }

.				{yyerror("lexer");}		// undetected char

%%


